apiVersion: v1.1
kind: Pod
metadata:
  name: myapp-pod
  labels:
      app: myapp
      type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx  


# kubectl create -f pod.yml
# kubectl get pod
# kubectl describe pod nginx
# kubectl get pods -o wide